/*
  HIGH STAKES TRUTH — EDITABLE FACT BANK

  Add or edit entries using this format:

  {
    text: "The claim shown to the player.",
    answer: true, // true or false
    explanation: "The explanation shown after the reveal.",
    category: "Science",
    difficulty: 2 // 1 = Common, 2 = Tricky, 3 = Deep Cut
  }

  Keep claims unambiguous. If a fact needs several caveats to be fair,
  rewrite it before adding it to the game.
*/

export const HST_FACTS = [
  {text:"Octopuses have three hearts.",answer:true,explanation:"Two hearts pump blood to the gills, while a third circulates blood through the rest of the body.",category:"Animals",difficulty:1},
  {text:"The Great Wall of China is visible from the Moon with the naked eye.",answer:false,explanation:"It is far too narrow to be seen from the Moon without aid.",category:"World",difficulty:1},
  {text:"Bananas are berries, but strawberries are not.",answer:true,explanation:"Botanically, bananas meet the definition of a berry. Strawberries are aggregate fruits.",category:"Food",difficulty:2},
  {text:"The unicorn is Scotland's national animal.",answer:true,explanation:"Scotland adopted the unicorn as a national symbol centuries ago.",category:"World",difficulty:1},
  {text:"Sharks existed before trees.",answer:true,explanation:"Sharks appeared more than 400 million years ago; trees appeared later.",category:"Animals",difficulty:2},
  {text:"A day on Venus is longer than a year on Venus.",answer:true,explanation:"Venus rotates so slowly that one rotation takes longer than one orbit around the Sun.",category:"Space",difficulty:2},
  {text:"Goldfish have a three-second memory.",answer:false,explanation:"Goldfish can remember things for weeks or even months.",category:"Animals",difficulty:1},
  {text:"The Eiffel Tower grows taller in summer.",answer:true,explanation:"Heat causes the metal to expand, increasing its height by several centimeters.",category:"World",difficulty:1},
  {text:"Napoleon was unusually short for his time.",answer:false,explanation:"He was around average height for a Frenchman of his era.",category:"History",difficulty:1},
  {text:"The first computer mouse was made of wood.",answer:true,explanation:"Douglas Engelbart's early mouse prototype used a wooden shell.",category:"Technology",difficulty:2},
  {text:"Lightning never strikes the same place twice.",answer:false,explanation:"Tall structures are often struck repeatedly.",category:"Science",difficulty:1},
  {text:"Wombat droppings are cube-shaped.",answer:true,explanation:"Their intestines compress the waste into distinct cube shapes.",category:"Animals",difficulty:1},
  {text:"Oxford University is older than the Aztec Empire.",answer:true,explanation:"Teaching at Oxford dates to the 11th century; the Aztec Empire formed in the 15th.",category:"History",difficulty:2},
  {text:"Humans use only ten percent of their brains.",answer:false,explanation:"Brain imaging shows activity throughout the brain, even during simple tasks and rest.",category:"Body",difficulty:1},
  {text:"Bulls become angry when they see the color red.",answer:false,explanation:"Bulls react to movement, not the color red; cattle are red-green colorblind.",category:"Animals",difficulty:1},
  {text:"The hottest planet in our solar system is Mercury.",answer:false,explanation:"Venus is hotter because its dense atmosphere traps heat.",category:"Space",difficulty:1},
  {text:"A group of flamingos is called a flamboyance.",answer:true,explanation:"Flamboyance is the commonly used collective noun for flamingos.",category:"Animals",difficulty:1},
  {text:"The Statue of Liberty was a gift from France.",answer:true,explanation:"France gifted the statue to the United States, and it was dedicated in 1886.",category:"History",difficulty:1},
  {text:"Glass is a slow-moving liquid.",answer:false,explanation:"Glass is an amorphous solid. Old windows are uneven because of historical manufacturing methods.",category:"Science",difficulty:2},
  {text:"A standard deck of cards contains 52 cards before jokers.",answer:true,explanation:"There are four suits with thirteen cards each.",category:"Games",difficulty:1},
  {text:"Nintendo was founded before the year 1900.",answer:true,explanation:"Nintendo began in 1889 as a playing-card company.",category:"Gaming",difficulty:2},
  {text:"The PlayStation 2 is the best-selling video game console ever.",answer:true,explanation:"It remains the best-selling console by total units sold.",category:"Gaming",difficulty:1},
  {text:"Pac-Man was inspired by a pizza missing a slice.",answer:true,explanation:"Creator Toru Iwatani has described the pizza shape as an inspiration.",category:"Gaming",difficulty:1},
  {text:"Tetris was created in the United States.",answer:false,explanation:"It was created in the Soviet Union by Alexey Pajitnov.",category:"Gaming",difficulty:1},
  {text:"Australia is wider than the Moon.",answer:true,explanation:"Australia spans roughly 4,000 km east to west; the Moon's diameter is about 3,475 km.",category:"World",difficulty:2},
  {text:"There are more pyramids in Sudan than in Egypt.",answer:true,explanation:"Sudan has hundreds of Nubian pyramids, more than Egypt.",category:"History",difficulty:2},
  {text:"The Amazon River is universally accepted as the world's longest river.",answer:false,explanation:"The Nile is usually listed as longest, though measurements and definitions remain debated.",category:"World",difficulty:2},
  {text:"The Pacific Ocean is larger than all Earth's land area combined.",answer:true,explanation:"The Pacific covers more surface area than all continents together.",category:"World",difficulty:2},
  {text:"Sound travels faster in water than in air.",answer:true,explanation:"Particles are closer together in water, allowing vibrations to move faster.",category:"Science",difficulty:1},
  {text:"Water expands when it freezes.",answer:true,explanation:"Ice forms an open crystal structure that takes up more space than liquid water.",category:"Science",difficulty:1},
  {text:"Oxygen itself is flammable.",answer:false,explanation:"Oxygen supports combustion but does not itself burn.",category:"Science",difficulty:2},
  {text:"HTML is a programming language.",answer:false,explanation:"HTML is a markup language used to structure content.",category:"Technology",difficulty:1},
  {text:"Wi-Fi officially stands for Wireless Fidelity.",answer:false,explanation:"Wi-Fi is a brand name and was not created as an acronym.",category:"Technology",difficulty:2},
  {text:"Amazon began as an online bookstore.",answer:true,explanation:"Books were Amazon's first major product category.",category:"Technology",difficulty:1},
  {text:"The QWERTY keyboard was designed purely to slow typists down.",answer:false,explanation:"Its history is more complicated; it was shaped by mechanical constraints and telegraph-era use.",category:"Technology",difficulty:3},
  {text:"Bats are blind.",answer:false,explanation:"Bats can see, and many species have excellent vision in addition to echolocation.",category:"Animals",difficulty:1},
  {text:"Cats cannot taste sweetness.",answer:true,explanation:"Cats lack a functioning receptor needed to taste sweet flavors.",category:"Animals",difficulty:2},
  {text:"Horses cannot vomit.",answer:true,explanation:"Their anatomy makes vomiting extremely difficult to impossible.",category:"Animals",difficulty:2},
  {text:"Birds are living dinosaurs.",answer:true,explanation:"Modern birds evolved from theropod dinosaurs.",category:"Animals",difficulty:2},
  {text:"Pterodactyls were dinosaurs.",answer:false,explanation:"They were flying reptiles called pterosaurs, not dinosaurs.",category:"History",difficulty:2},
  {text:"Cleopatra lived closer to the Moon landing than to the construction of the Great Pyramid.",answer:true,explanation:"The Great Pyramid was already ancient in Cleopatra's time.",category:"History",difficulty:2},
  {text:"France was still using the guillotine when the first Star Wars movie opened.",answer:true,explanation:"France's final guillotine execution occurred in 1977.",category:"History",difficulty:3},
  {text:"The shortest recorded war lasted less than one hour.",answer:true,explanation:"The Anglo-Zanzibar War of 1896 lasted roughly 38 to 45 minutes.",category:"History",difficulty:2},
  {text:"George Washington wore wooden dentures.",answer:false,explanation:"His dentures used materials such as ivory, metal, and human or animal teeth—not wood.",category:"History",difficulty:2},
  {text:"The forbidden fruit in Genesis is explicitly identified as an apple.",answer:false,explanation:"The text does not name the fruit.",category:"History",difficulty:1},
  {text:"Coffee beans are actually beans.",answer:false,explanation:"They are seeds found inside the fruit of the coffee plant.",category:"Food",difficulty:1},
  {text:"Cashews grow attached to a fruit.",answer:true,explanation:"The cashew seed grows beneath the cashew apple.",category:"Food",difficulty:2},
  {text:"All Froot Loops are the same flavor.",answer:true,explanation:"The colors differ, but the cereal pieces share one flavor profile.",category:"Food",difficulty:2},
  {text:"White chocolate contains cocoa solids.",answer:false,explanation:"It contains cocoa butter but not the cocoa solids found in dark or milk chocolate.",category:"Food",difficulty:2},
  {text:"Croissants originated in France.",answer:false,explanation:"Their roots trace to Austrian pastries, though France developed the modern croissant.",category:"Food",difficulty:2},
  {text:"Pineapples usually take more than a year to grow.",answer:true,explanation:"They often need around 18 to 24 months to mature.",category:"Food",difficulty:1},
  {text:"The human body has 206 bones in adulthood.",answer:true,explanation:"Most adults have 206 bones, though natural variation exists.",category:"Body",difficulty:1},
  {text:"Blood inside your veins is blue.",answer:false,explanation:"Human blood is always red; veins look blue because of how light passes through skin.",category:"Body",difficulty:1},
  {text:"The skin is the body's largest organ.",answer:true,explanation:"By surface area and weight, skin is the largest organ.",category:"Body",difficulty:1},
  {text:"Hair and fingernails keep growing after death.",answer:false,explanation:"Skin dehydration can make them appear longer, but growth stops.",category:"Body",difficulty:1},
  {text:"Your left lung is smaller than your right lung.",answer:true,explanation:"The left lung makes room for the heart.",category:"Body",difficulty:1},
  {text:"Humans are born with more bones than they have as adults.",answer:true,explanation:"Many infant bones fuse together during growth.",category:"Body",difficulty:1},
  {text:"A tomato contains more genes than a human.",answer:true,explanation:"Tomatoes have roughly 31,000 genes, more than humans.",category:"Science",difficulty:3},
  {text:"Time passes slightly faster at the top of a mountain.",answer:true,explanation:"According to relativity, clocks run slightly faster farther from Earth's gravity.",category:"Science",difficulty:3},
  {text:"Black holes are empty holes in space.",answer:false,explanation:"They are regions where matter and energy are compressed so densely that gravity becomes extreme.",category:"Space",difficulty:2},
  {text:"Space is completely silent.",answer:true,explanation:"Sound waves require a medium, and space is nearly a vacuum.",category:"Space",difficulty:1},
  {text:"Saturn is the only planet with rings.",answer:false,explanation:"Jupiter, Uranus, and Neptune also have ring systems.",category:"Space",difficulty:1},
  {text:"Astronauts can temporarily grow taller in space.",answer:true,explanation:"Reduced gravity allows the spine to expand.",category:"Space",difficulty:1},
  {text:"A light-year measures time.",answer:false,explanation:"A light-year is a unit of distance.",category:"Space",difficulty:1},
  {text:"Mars appears red because of iron oxide.",answer:true,explanation:"Iron minerals in Martian soil oxidize, creating a rusty color.",category:"Space",difficulty:1},
  {text:"The Moon has a permanently dark side.",answer:false,explanation:"All sides receive sunlight; one side is simply always facing away from Earth.",category:"Space",difficulty:1},
  {text:"The Sun is naturally white.",answer:true,explanation:"From space, sunlight appears white; Earth's atmosphere can make it look yellow or orange.",category:"Space",difficulty:2},
  {text:"Vatican City is the world's smallest independent country.",answer:true,explanation:"It is the smallest by both area and population.",category:"World",difficulty:1},
  {text:"Toronto is the capital of Canada.",answer:false,explanation:"Ottawa is Canada's capital.",category:"World",difficulty:1},
  {text:"Antarctica is the world's largest desert.",answer:true,explanation:"Deserts are defined by low precipitation, not temperature.",category:"World",difficulty:2},
  {text:"The Statue of Liberty is located in Washington, D.C.",answer:false,explanation:"It stands in New York Harbor.",category:"World",difficulty:1},
  {text:"A standard bowling game contains ten frames.",answer:true,explanation:"A normal game is ten frames long.",category:"Sports",difficulty:1},
  {text:"Golf balls were once stuffed with feathers.",answer:true,explanation:"Early 'feathery' balls used leather shells packed with feathers.",category:"Sports",difficulty:2},
  {text:"Michael Jordan spent his entire NBA career with the Chicago Bulls.",answer:false,explanation:"He also played for the Washington Wizards.",category:"Sports",difficulty:1},
  {text:"The first modern Olympic Games were held in Athens.",answer:true,explanation:"The first modern Olympics took place in Athens in 1896.",category:"Sports",difficulty:1}
];
