/*
  HIGH STAKES TRUTH — EDITABLE FACT BANK

  Add or edit entries using this format:

  {
    text: "The claim shown to the player.",
    answer: true, // true or false
    explanation: "The explanation shown after the reveal.",
    category: "Science",
    difficulty: 2 // 1 = Common, 2 = Tricky, 3 = Deep Cut
  }

  Keep claims unambiguous. If a fact needs several caveats to be fair,
  rewrite it before adding it to the game.
*/

window HST_FACTS = [
  // ---------- ORIGINAL FACTS ----------
  {text:"Octopuses have three hearts.",answer:true,explanation:"Two hearts pump blood to the gills, while a third circulates blood through the rest of the body.",category:"Animals",difficulty:1},
  {text:"The Great Wall of China is visible from the Moon with the naked eye.",answer:false,explanation:"It is far too narrow to be seen from the Moon without aid.",category:"World",difficulty:1},
  {text:"Bananas are berries, but strawberries are not.",answer:true,explanation:"Botanically, bananas meet the definition of a berry. Strawberries are aggregate fruits.",category:"Food",difficulty:2},
  {text:"The unicorn is Scotland's national animal.",answer:true,explanation:"Scotland adopted the unicorn as a national symbol centuries ago.",category:"World",difficulty:1},
  {text:"Sharks existed before trees.",answer:true,explanation:"Sharks appeared more than 400 million years ago; trees appeared later.",category:"Animals",difficulty:2},
  {text:"A day on Venus is longer than a year on Venus.",answer:true,explanation:"Venus rotates so slowly that one rotation takes longer than one orbit around the Sun.",category:"Space",difficulty:2},
  {text:"Goldfish have a three-second memory.",answer:false,explanation:"Goldfish can remember things for weeks or even months.",category:"Animals",difficulty:1},
  {text:"The Eiffel Tower grows taller in summer.",answer:true,explanation:"Heat causes the metal to expand, increasing its height by several centimeters.",category:"World",difficulty:1},
  {text:"Napoleon was unusually short for his time.",answer:false,explanation:"He was around average height for a Frenchman of his era.",category:"History",difficulty:1},
  {text:"The first computer mouse was made of wood.",answer:true,explanation:"Douglas Engelbart's early mouse prototype used a wooden shell.",category:"Technology",difficulty:2},
  {text:"Lightning never strikes the same place twice.",answer:false,explanation:"Tall structures are often struck repeatedly.",category:"Science",difficulty:1},
  {text:"Wombat droppings are cube-shaped.",answer:true,explanation:"Their intestines compress the waste into distinct cube shapes.",category:"Animals",difficulty:1},
  {text:"Oxford University is older than the Aztec Empire.",answer:true,explanation:"Teaching at Oxford dates to the 11th century; the Aztec Empire formed in the 15th.",category:"History",difficulty:2},
  {text:"Humans use only ten percent of their brains.",answer:false,explanation:"Brain imaging shows activity throughout the brain, even during simple tasks and rest.",category:"Body",difficulty:1},
  {text:"Bulls become angry when they see the color red.",answer:false,explanation:"Bulls react to movement, not the color red; cattle are red-green colorblind.",category:"Animals",difficulty:1},
  {text:"The hottest planet in our solar system is Mercury.",answer:false,explanation:"Venus is hotter because its dense atmosphere traps heat.",category:"Space",difficulty:1},
  {text:"A group of flamingos is called a flamboyance.",answer:true,explanation:"Flamboyance is the commonly used collective noun for flamingos.",category:"Animals",difficulty:1},
  {text:"The Statue of Liberty was a gift from France.",answer:true,explanation:"France gifted the statue to the United States, and it was dedicated in 1886.",category:"History",difficulty:1},
  {text:"Glass is a slow-moving liquid.",answer:false,explanation:"Glass is an amorphous solid. Old windows are uneven because of historical manufacturing methods.",category:"Science",difficulty:2},
  {text:"A standard deck of cards contains 52 cards before jokers.",answer:true,explanation:"There are four suits with thirteen cards each.",category:"Games",difficulty:1},
  {text:"Nintendo was founded before the year 1900.",answer:true,explanation:"Nintendo began in 1889 as a playing-card company.",category:"Gaming",difficulty:2},
  {text:"The PlayStation 2 is the best-selling video game console ever.",answer:true,explanation:"It remains the best-selling console by total units sold.",category:"Gaming",difficulty:1},
  {text:"Pac-Man was inspired by a pizza missing a slice.",answer:true,explanation:"Creator Toru Iwatani has described the pizza shape as an inspiration.",category:"Gaming",difficulty:1},
  {text:"Tetris was created in the United States.",answer:false,explanation:"It was created in the Soviet Union by Alexey Pajitnov.",category:"Gaming",difficulty:1},
  {text:"Australia is wider than the Moon.",answer:true,explanation:"Australia spans roughly 4,000 km east to west; the Moon's diameter is about 3,475 km.",category:"World",difficulty:2},
  {text:"There are more pyramids in Sudan than in Egypt.",answer:true,explanation:"Sudan has hundreds of Nubian pyramids, more than Egypt.",category:"History",difficulty:2},
  {text:"The Amazon River is universally accepted as the world's longest river.",answer:false,explanation:"The Nile is usually listed as longest, though measurements and definitions remain debated.",category:"World",difficulty:2},
  {text:"The Pacific Ocean is larger than all Earth's land area combined.",answer:true,explanation:"The Pacific covers more surface area than all continents together.",category:"World",difficulty:2},
  {text:"Sound travels faster in water than in air.",answer:true,explanation:"Particles are closer together in water, allowing vibrations to move faster.",category:"Science",difficulty:1},
  {text:"Water expands when it freezes.",answer:true,explanation:"Ice forms an open crystal structure that takes up more space than liquid water.",category:"Science",difficulty:1},
  {text:"Oxygen itself is flammable.",answer:false,explanation:"Oxygen supports combustion but does not itself burn.",category:"Science",difficulty:2},
  {text:"HTML is a programming language.",answer:false,explanation:"HTML is a markup language used to structure content.",category:"Technology",difficulty:1},
  {text:"Wi-Fi officially stands for Wireless Fidelity.",answer:false,explanation:"Wi-Fi is a brand name and was not created as an acronym.",category:"Technology",difficulty:2},
  {text:"Amazon began as an online bookstore.",answer:true,explanation:"Books were Amazon's first major product category.",category:"Technology",difficulty:1},
  {text:"The QWERTY keyboard was designed purely to slow typists down.",answer:false,explanation:"Its history is more complicated; it was shaped by mechanical constraints and telegraph-era use.",category:"Technology",difficulty:3},
  {text:"Bats are blind.",answer:false,explanation:"Bats can see, and many species have excellent vision in addition to echolocation.",category:"Animals",difficulty:1},
  {text:"Cats cannot taste sweetness.",answer:true,explanation:"Cats lack a functioning receptor needed to taste sweet flavors.",category:"Animals",difficulty:2},
  {text:"Horses cannot vomit.",answer:true,explanation:"Their anatomy makes vomiting extremely difficult to impossible.",category:"Animals",difficulty:2},
  {text:"Birds are living dinosaurs.",answer:true,explanation:"Modern birds evolved from theropod dinosaurs.",category:"Animals",difficulty:2},
  {text:"Pterodactyls were dinosaurs.",answer:false,explanation:"They were flying reptiles called pterosaurs, not dinosaurs.",category:"History",difficulty:2},
  {text:"Cleopatra lived closer to the Moon landing than to the construction of the Great Pyramid.",answer:true,explanation:"The Great Pyramid was already ancient in Cleopatra's time.",category:"History",difficulty:2},
  {text:"France was still using the guillotine when the first Star Wars movie opened.",answer:true,explanation:"France's final guillotine execution occurred in 1977.",category:"History",difficulty:3},
  {text:"The shortest recorded war lasted less than one hour.",answer:true,explanation:"The Anglo-Zanzibar War of 1896 lasted roughly 38 to 45 minutes.",category:"History",difficulty:2},
  {text:"George Washington wore wooden dentures.",answer:false,explanation:"His dentures used materials such as ivory, metal, and human or animal teeth—not wood.",category:"History",difficulty:2},
  {text:"The forbidden fruit in Genesis is explicitly identified as an apple.",answer:false,explanation:"The text does not name the fruit.",category:"History",difficulty:1},
  {text:"Coffee beans are actually beans.",answer:false,explanation:"They are seeds found inside the fruit of the coffee plant.",category:"Food",difficulty:1},
  {text:"Cashews grow attached to a fruit.",answer:true,explanation:"The cashew seed grows beneath the cashew apple.",category:"Food",difficulty:2},
  {text:"All Froot Loops are the same flavor.",answer:true,explanation:"The colors differ, but the cereal pieces share one flavor profile.",category:"Food",difficulty:2},
  {text:"White chocolate contains cocoa solids.",answer:false,explanation:"It contains cocoa butter but not the cocoa solids found in dark or milk chocolate.",category:"Food",difficulty:2},
  {text:"Croissants originated in France.",answer:false,explanation:"Their roots trace to Austrian pastries, though France developed the modern croissant.",category:"Food",difficulty:2},
  {text:"Pineapples usually take more than a year to grow.",answer:true,explanation:"They often need around 18 to 24 months to mature.",category:"Food",difficulty:1},
  {text:"The human body has 206 bones in adulthood.",answer:true,explanation:"Most adults have 206 bones, though natural variation exists.",category:"Body",difficulty:1},
  {text:"Blood inside your veins is blue.",answer:false,explanation:"Human blood is always red; veins look blue because of how light passes through skin.",category:"Body",difficulty:1},
  {text:"The skin is the body's largest organ.",answer:true,explanation:"By surface area and weight, skin is the largest organ.",category:"Body",difficulty:1},
  {text:"Hair and fingernails keep growing after death.",answer:false,explanation:"Skin dehydration can make them appear longer, but growth stops.",category:"Body",difficulty:1},
  {text:"Your left lung is smaller than your right lung.",answer:true,explanation:"The left lung makes room for the heart.",category:"Body",difficulty:1},
  {text:"Humans are born with more bones than they have as adults.",answer:true,explanation:"Many infant bones fuse together during growth.",category:"Body",difficulty:1},
  {text:"A tomato contains more genes than a human.",answer:true,explanation:"Tomatoes have roughly 31,000 genes, more than humans.",category:"Science",difficulty:3},
  {text:"Time passes slightly faster at the top of a mountain.",answer:true,explanation:"According to relativity, clocks run slightly faster farther from Earth's gravity.",category:"Science",difficulty:3},
  {text:"Black holes are empty holes in space.",answer:false,explanation:"They are regions where matter and energy are compressed so densely that gravity becomes extreme.",category:"Space",difficulty:2},
  {text:"Space is completely silent.",answer:true,explanation:"Sound waves require a medium, and space is nearly a vacuum.",category:"Space",difficulty:1},
  {text:"Saturn is the only planet with rings.",answer:false,explanation:"Jupiter, Uranus, and Neptune also have ring systems.",category:"Space",difficulty:1},
  {text:"Astronauts can temporarily grow taller in space.",answer:true,explanation:"Reduced gravity allows the spine to expand.",category:"Space",difficulty:1},
  {text:"A light-year measures time.",answer:false,explanation:"A light-year is a unit of distance.",category:"Space",difficulty:1},
  {text:"Mars appears red because of iron oxide.",answer:true,explanation:"Iron minerals in Martian soil oxidize, creating a rusty color.",category:"Space",difficulty:1},
  {text:"The Moon has a permanently dark side.",answer:false,explanation:"All sides receive sunlight; one side is simply always facing away from Earth.",category:"Space",difficulty:1},
  {text:"The Sun is naturally white.",answer:true,explanation:"From space, sunlight appears white; Earth's atmosphere can make it look yellow or orange.",category:"Space",difficulty:2},
  {text:"Vatican City is the world's smallest independent country.",answer:true,explanation:"It is the smallest by both area and population.",category:"World",difficulty:1},
  {text:"Toronto is the capital of Canada.",answer:false,explanation:"Ottawa is Canada's capital.",category:"World",difficulty:1},
  {text:"Antarctica is the world's largest desert.",answer:true,explanation:"Deserts are defined by low precipitation, not temperature.",category:"World",difficulty:2},
  {text:"The Statue of Liberty is located in Washington, D.C.",answer:false,explanation:"It stands in New York Harbor.",category:"World",difficulty:1},
  {text:"A standard bowling game contains ten frames.",answer:true,explanation:"A normal game is ten frames long.",category:"Sports",difficulty:1},
  {text:"Golf balls were once stuffed with feathers.",answer:true,explanation:"Early 'feathery' balls used leather shells packed with feathers.",category:"Sports",difficulty:2},
  {text:"Michael Jordan spent his entire NBA career with the Chicago Bulls.",answer:false,explanation:"He also played for the Washington Wizards.",category:"Sports",difficulty:1},
  {text:"The first modern Olympic Games were held in Athens.",answer:true,explanation:"The first modern Olympics took place in Athens in 1896.",category:"Sports",difficulty:1},

  // ---------- NEW: ANIMALS ----------
  {text:"A shrimp's heart is located in its head.",answer:true,explanation:"A shrimp's heart sits in the thorax, just behind its head region.",category:"Animals",difficulty:2},
  {text:"Starfish have no brain.",answer:true,explanation:"Instead of a brain, they have a decentralized nerve network.",category:"Animals",difficulty:2},
  {text:"Adult elephants are unable to jump.",answer:true,explanation:"Their weight and leg structure keep all feet from leaving the ground at once.",category:"Animals",difficulty:2},
  {text:"A crocodile cannot stick its tongue out.",answer:true,explanation:"Its tongue is anchored to the bottom of its mouth.",category:"Animals",difficulty:2},
  {text:"Owls cannot move their eyeballs within their sockets.",answer:true,explanation:"Their eyes are fixed, so they rotate their heads instead.",category:"Animals",difficulty:2},
  {text:"A group of crows is called a murder.",answer:true,explanation:"Murder is the traditional collective noun for crows.",category:"Animals",difficulty:1},
  {text:"Cattle can form close bonds resembling best friendships.",answer:true,explanation:"Studies show cows become calmer when kept near a preferred companion.",category:"Animals",difficulty:3},
  {text:"A hummingbird can fly backward.",answer:true,explanation:"Their unique wing motion lets them fly backward and hover.",category:"Animals",difficulty:1},
  {text:"Penguins can drink seawater.",answer:true,explanation:"A special gland filters and removes excess salt.",category:"Animals",difficulty:2},
  {text:"Sea otters sometimes hold hands while sleeping.",answer:true,explanation:"They do this to keep from drifting apart in the water.",category:"Animals",difficulty:1},
  {text:"Butterflies taste with their feet.",answer:true,explanation:"Taste sensors on their feet help them identify suitable plants.",category:"Animals",difficulty:2},
  {text:"An ostrich's eye is larger than its brain.",answer:true,explanation:"Ostriches have unusually large eyes for their body size.",category:"Animals",difficulty:2},
  {text:"Some Arctic reindeer have eyes that change color between summer and winter.",answer:true,explanation:"Their eye tissue shifts from gold to blue to cope with changing light.",category:"Animals",difficulty:3},
  {text:"A tiger's skin is striped, not just its fur.",answer:true,explanation:"The stripe pattern is present on the skin beneath the fur.",category:"Animals",difficulty:2},
  {text:"Polar bears have black skin.",answer:true,explanation:"Their skin is black beneath fur that only appears white.",category:"Animals",difficulty:2},
  {text:"Giraffes have the same number of neck vertebrae as humans.",answer:true,explanation:"Both have seven neck vertebrae; a giraffe's are just much larger.",category:"Animals",difficulty:2},
  {text:"Some snakes are born with two heads.",answer:true,explanation:"This rare condition, called bicephaly, does occur in snakes.",category:"Animals",difficulty:2},
  {text:"A jellyfish is roughly 95 percent water.",answer:true,explanation:"Most of a jellyfish's body is water, giving it a gelatinous form.",category:"Animals",difficulty:1},
  {text:"Male seahorses carry and give birth to their young.",answer:true,explanation:"Females deposit eggs into a pouch on the male, who then gives birth.",category:"Animals",difficulty:2},
  {text:"Dolphins use signature whistles that work like names.",answer:true,explanation:"Each dolphin develops a unique whistle others use to address it.",category:"Animals",difficulty:2},
  {text:"A snail can have thousands of tiny teeth.",answer:true,explanation:"Snails feed using a radula covered in rows of microscopic teeth.",category:"Animals",difficulty:2},
  {text:"Flamingos are not born pink.",answer:true,explanation:"They hatch grey or white and turn pink from pigments in their diet.",category:"Animals",difficulty:1},
  {text:"Elephants can recognize themselves in a mirror.",answer:true,explanation:"They are among the few animals shown to pass mirror self-recognition tests.",category:"Animals",difficulty:2},
  {text:"The blue whale is the largest animal known to have ever lived.",answer:true,explanation:"No known animal, past or present, has exceeded the blue whale's size.",category:"Animals",difficulty:1},
  {text:"A blue whale's tongue can weigh about as much as an elephant.",answer:true,explanation:"The tongue alone can weigh several thousand pounds.",category:"Animals",difficulty:3},
  {text:"Ants do not have lungs.",answer:true,explanation:"They breathe through tiny holes called spiracles along their bodies.",category:"Animals",difficulty:2},
  {text:"A group of owls is called a parliament.",answer:true,explanation:"Parliament is the traditional collective noun for owls.",category:"Animals",difficulty:1},
  {text:"Rats have been shown to make laughter-like sounds when tickled.",answer:true,explanation:"Researchers recorded high-frequency chirps during tickling play.",category:"Animals",difficulty:3},
  {text:"Many sea stars can regrow a lost arm.",answer:true,explanation:"Some species can even regenerate an entire body from one arm.",category:"Animals",difficulty:2},
  {text:"Chameleons change color mainly to communicate and regulate temperature.",answer:true,explanation:"Color shifts signal mood and control heat more than they camouflage.",category:"Animals",difficulty:3},
  {text:"In a lion pride, the males do most of the hunting.",answer:false,explanation:"Lionesses handle the majority of hunting for the pride.",category:"Animals",difficulty:1},
  {text:"Dogs sweat mostly through their paws.",answer:true,explanation:"Sweat glands in their paw pads help release heat.",category:"Animals",difficulty:2},
  {text:"Cheetahs are unable to roar.",answer:true,explanation:"They lack the vocal structure to roar but can purr and chirp.",category:"Animals",difficulty:2},
  {text:"Camels store water in their humps.",answer:false,explanation:"Their humps store fat, not water.",category:"Animals",difficulty:1},
  {text:"Wild turkeys can fly.",answer:true,explanation:"Wild turkeys can fly short distances at surprising speed.",category:"Animals",difficulty:2},
  {text:"Only female mosquitoes bite humans.",answer:true,explanation:"Females need blood to produce eggs; males feed on nectar.",category:"Animals",difficulty:2},
  {text:"Koalas can sleep up to around 20 hours a day.",answer:true,explanation:"Their low-energy eucalyptus diet leads to long sleep periods.",category:"Animals",difficulty:1},
  {text:"Octopuses have blue blood.",answer:true,explanation:"Their blood uses a copper-based molecule that appears blue.",category:"Animals",difficulty:2},
  {text:"Spiders are insects.",answer:false,explanation:"Spiders are arachnids; they have eight legs and two body segments.",category:"Animals",difficulty:1},
  {text:"All insects have six legs.",answer:true,explanation:"Having six legs is part of the definition of an insect.",category:"Animals",difficulty:1},
  {text:"Every centipede has exactly one hundred legs.",answer:false,explanation:"Leg counts vary widely; few centipedes have exactly 100.",category:"Animals",difficulty:2},
  {text:"A ladybug is a type of beetle.",answer:true,explanation:"Ladybugs belong to the beetle family Coccinellidae.",category:"Animals",difficulty:2},
  {text:"Honeybees have been shown to recognize human faces.",answer:true,explanation:"Trained bees can learn to distinguish between different face patterns.",category:"Animals",difficulty:3},
  {text:"The bumblebee bat is among the smallest mammals in the world.",answer:true,explanation:"It weighs about as much as a small coin.",category:"Animals",difficulty:2},
  {text:"A group of jellyfish can be called a smack.",answer:true,explanation:"Smack is one accepted collective noun for jellyfish.",category:"Animals",difficulty:2},
  {text:"Koala fingerprints are very similar to human fingerprints.",answer:true,explanation:"They are so alike they can be hard to tell apart under a microscope.",category:"Animals",difficulty:3},
  {text:"Slugs and snails leave slime that lets them cross sharp surfaces unharmed.",answer:true,explanation:"Their protective mucus lets them travel over edges like a blade safely.",category:"Animals",difficulty:2},
  {text:"Ants can carry many times their own body weight.",answer:true,explanation:"Their small size and muscle structure allow outsized strength.",category:"Animals",difficulty:1},
  {text:"Lions can roar loudly enough to be heard several kilometers away.",answer:true,explanation:"A lion's roar can carry roughly five miles across open land.",category:"Animals",difficulty:2},

  // ---------- NEW: SPACE ----------
  {text:"Roughly a million Earths could fit inside the Sun.",answer:true,explanation:"By volume, the Sun could hold well over a million Earths.",category:"Space",difficulty:2},
  {text:"A teaspoon of neutron-star material would weigh billions of tons.",answer:true,explanation:"Neutron stars are so dense that a tiny amount has enormous mass.",category:"Space",difficulty:3},
  {text:"Jupiter is the largest planet in the solar system.",answer:true,explanation:"Jupiter's mass is greater than all other planets combined.",category:"Space",difficulty:1},
  {text:"The footprints left on the Moon could last for millions of years.",answer:true,explanation:"With no wind or water, there is little to erode them.",category:"Space",difficulty:2},
  {text:"A year on Mercury lasts only about 88 Earth days.",answer:true,explanation:"Mercury orbits the Sun far faster than Earth does.",category:"Space",difficulty:2},
  {text:"The Sun makes up more than 99 percent of the solar system's mass.",answer:true,explanation:"Everything else combined is a tiny fraction of the total.",category:"Space",difficulty:2},
  {text:"Olympus Mons on Mars is the tallest known volcano in the solar system.",answer:true,explanation:"It rises far higher than any mountain on Earth.",category:"Space",difficulty:2},
  {text:"Saturn is less dense than water.",answer:true,explanation:"If a large enough ocean existed, Saturn would float in it.",category:"Space",difficulty:3},
  {text:"There are more stars in the universe than grains of sand on all of Earth's beaches.",answer:true,explanation:"Estimates put the star count far beyond Earth's sand grains.",category:"Space",difficulty:2},
  {text:"Venus rotates in the opposite direction to most planets.",answer:true,explanation:"Venus spins clockwise, unlike most planets in the solar system.",category:"Space",difficulty:2},
  {text:"Pluto has not completed a full orbit of the Sun since it was discovered.",answer:true,explanation:"Its orbit takes about 248 years; it was found in 1930.",category:"Space",difficulty:3},
  {text:"Neptune's existence was predicted by mathematics before it was seen.",answer:true,explanation:"Astronomers calculated its position from irregularities in Uranus's orbit.",category:"Space",difficulty:3},
  {text:"Uranus rotates on its side compared to most planets.",answer:true,explanation:"Its axis is tilted almost 90 degrees.",category:"Space",difficulty:2},
  {text:"The International Space Station orbits Earth about once every 90 minutes.",answer:true,explanation:"It circles the planet roughly 16 times per day.",category:"Space",difficulty:2},
  {text:"Halley's Comet becomes visible from Earth about every 76 years.",answer:true,explanation:"Its long orbit brings it near Earth roughly once a human lifetime.",category:"Space",difficulty:2},
  {text:"The Milky Way and Andromeda galaxies are moving toward a future collision.",answer:true,explanation:"They are expected to merge billions of years from now.",category:"Space",difficulty:3},
  {text:"Jupiter's Great Red Spot is a storm larger than Earth.",answer:true,explanation:"This giant storm has raged for centuries and dwarfs our planet.",category:"Space",difficulty:2},
  {text:"Mercury is the closest planet to the Sun.",answer:true,explanation:"No planet orbits nearer to the Sun than Mercury.",category:"Space",difficulty:1},
  {text:"Astronauts have reported that space has a distinct smell like seared metal or gunpowder.",answer:true,explanation:"They describe a lingering odor on gear brought back inside.",category:"Space",difficulty:3},
  {text:"The Moon has no wind or weather.",answer:true,explanation:"Without a real atmosphere, there is no wind or weather on the Moon.",category:"Space",difficulty:2},
  {text:"Some known stars are larger than the entire orbit of Jupiter around the Sun.",answer:true,explanation:"The biggest hypergiant stars are staggeringly large.",category:"Space",difficulty:3},

  // ---------- NEW: SCIENCE ----------
  {text:"Under certain conditions, hot water can freeze faster than cold water.",answer:true,explanation:"This surprising effect is known as the Mpemba effect.",category:"Science",difficulty:3},
  {text:"Diamonds are made of carbon.",answer:true,explanation:"They form from carbon under intense heat and pressure.",category:"Science",difficulty:1},
  {text:"A bolt of lightning is hotter than the surface of the Sun.",answer:true,explanation:"Lightning can briefly reach temperatures several times hotter than the Sun's surface.",category:"Science",difficulty:2},
  {text:"Metals generally expand when heated.",answer:true,explanation:"Heat increases the motion of atoms, spreading them apart.",category:"Science",difficulty:1},
  {text:"The chemical symbol for gold is Au.",answer:true,explanation:"Au comes from the Latin word for gold, aurum.",category:"Science",difficulty:2},
  {text:"Table salt is made from sodium and chlorine.",answer:true,explanation:"Common salt is the compound sodium chloride.",category:"Science",difficulty:1},
  {text:"Bananas are slightly radioactive.",answer:true,explanation:"They contain potassium, including a naturally radioactive form.",category:"Science",difficulty:2},
  {text:"The Earth is a perfect sphere.",answer:false,explanation:"It bulges slightly at the equator, making it an oblate spheroid.",category:"Science",difficulty:1},
  {text:"Gold is safe to eat in tiny edible-leaf amounts.",answer:true,explanation:"Pure edible gold leaf passes through the body without being absorbed.",category:"Science",difficulty:2},
  {text:"Water is at its densest at around 4 degrees Celsius.",answer:true,explanation:"This is why ice floats and lakes freeze from the top down.",category:"Science",difficulty:3},
  {text:"Natural rubber comes from trees.",answer:true,explanation:"It is made from latex tapped from rubber trees.",category:"Science",difficulty:1},
  {text:"Sunlight takes about eight minutes to reach Earth.",answer:true,explanation:"Light travels the Sun-to-Earth distance in roughly eight minutes.",category:"Science",difficulty:2},
  {text:"Diamond is the hardest naturally occurring material.",answer:true,explanation:"It sits at the top of the standard hardness scale.",category:"Science",difficulty:1},
  {text:"Mercury is the only metal that is liquid at room temperature.",answer:true,explanation:"Other metals need much higher temperatures to melt.",category:"Science",difficulty:2},
  {text:"Glass is made mostly from sand.",answer:true,explanation:"Silica sand is the main ingredient in ordinary glass.",category:"Science",difficulty:1},
  {text:"Ultraviolet light is invisible to the human eye.",answer:true,explanation:"Its wavelengths fall just outside the range humans can see.",category:"Science",difficulty:2},
  {text:"Sound travels faster through steel than through air.",answer:true,explanation:"Denser, more rigid materials transmit sound faster.",category:"Science",difficulty:2},
  {text:"Photosynthesis releases oxygen.",answer:true,explanation:"Plants produce oxygen as a byproduct of making food from light.",category:"Science",difficulty:1},
  {text:"Rust is a form of oxidation.",answer:true,explanation:"Iron reacts with oxygen and moisture to form rust.",category:"Science",difficulty:1},
  {text:"Helium can temporarily raise the pitch of your voice.",answer:true,explanation:"Sound travels faster through helium, changing how your voice resonates.",category:"Science",difficulty:2},
  {text:"Absolute zero is the coldest temperature that can exist.",answer:true,explanation:"At absolute zero, atomic motion reaches its theoretical minimum.",category:"Science",difficulty:2},

  // ---------- NEW: BODY ----------
  {text:"The human heart beats roughly 100,000 times a day.",answer:true,explanation:"That adds up to millions of beats per year.",category:"Body",difficulty:2},
  {text:"The stomach regularly builds a new lining to avoid digesting itself.",answer:true,explanation:"Its protective lining is replaced often to resist strong acid.",category:"Body",difficulty:3},
  {text:"The masseter, a jaw muscle, is one of the strongest muscles for its size.",answer:true,explanation:"It can generate remarkable bite force relative to its size.",category:"Body",difficulty:3},
  {text:"The human body contains roughly as many bacterial cells as human cells.",answer:true,explanation:"Recent estimates put the ratio at close to one to one.",category:"Body",difficulty:3},
  {text:"Fingernails grow faster than toenails.",answer:true,explanation:"Nails on the hands typically grow noticeably faster.",category:"Body",difficulty:2},
  {text:"The human nose can distinguish more than a trillion different smells.",answer:true,explanation:"A study estimated the number of detectable scents in the trillions.",category:"Body",difficulty:3},
  {text:"Your ears and nose continue growing throughout life.",answer:true,explanation:"Their cartilage keeps changing shape as you age.",category:"Body",difficulty:2},
  {text:"Taste buds are replaced roughly every couple of weeks.",answer:true,explanation:"Taste cells regularly die off and regenerate.",category:"Body",difficulty:3},
  {text:"The small intestine is longer than the large intestine.",answer:true,explanation:"Despite its name, the small intestine is much longer.",category:"Body",difficulty:2},
  {text:"The human body gives off a faint glow too dim for the eye to see.",answer:true,explanation:"Sensitive cameras have detected extremely weak human bioluminescence.",category:"Body",difficulty:3},
  {text:"The cornea of the eye has no blood supply.",answer:true,explanation:"It gets oxygen directly from the air instead of blood vessels.",category:"Body",difficulty:3},
  {text:"The femur is the longest bone in the human body.",answer:true,explanation:"The thigh bone is the longest and strongest bone we have.",category:"Body",difficulty:1},
  {text:"Stomach acid is strong enough to damage some metals.",answer:true,explanation:"It contains hydrochloric acid, which is highly corrosive.",category:"Body",difficulty:2},
  {text:"Most people cannot tickle themselves.",answer:true,explanation:"The brain predicts self-touch and dampens the sensation.",category:"Body",difficulty:2},
  {text:"The brain uses around a fifth of the body's energy.",answer:true,explanation:"Despite its size, the brain is very energy-hungry.",category:"Body",difficulty:2},
  {text:"The tongue is the strongest muscle in the human body.",answer:false,explanation:"This is a myth; the tongue is strong but not the strongest.",category:"Body",difficulty:2},
  {text:"Humans are the only animals with a true chin.",answer:true,explanation:"The bony chin is a feature unique to modern humans.",category:"Body",difficulty:3},
  {text:"Mature red blood cells have no nucleus.",answer:true,explanation:"They lose their nucleus to carry more oxygen.",category:"Body",difficulty:3},
  {text:"The adult heart is roughly the size of a clenched fist.",answer:true,explanation:"An average heart is about the size of a fist.",category:"Body",difficulty:1},
  {text:"Newborns generally do not shed tears for their first few weeks.",answer:true,explanation:"Their tear ducts take time to fully develop.",category:"Body",difficulty:2},
  {text:"Fingerprints are unique to each individual.",answer:true,explanation:"No two people are known to share the same fingerprints.",category:"Body",difficulty:1},
  {text:"Goosebumps are a leftover reflex from our distant ancestors.",answer:true,explanation:"They once helped raise fur for warmth or to appear larger.",category:"Body",difficulty:2},

  // ---------- NEW: FOOD ----------
  {text:"Honey recovered from ancient Egyptian tombs was still edible.",answer:true,explanation:"Honey's chemistry lets it last virtually forever.",category:"Food",difficulty:2},
  {text:"Carrots were originally mostly purple, not orange.",answer:true,explanation:"Orange carrots were developed later through cultivation.",category:"Food",difficulty:3},
  {text:"Ketchup was once sold as medicine.",answer:true,explanation:"In the 1800s tomato ketchup was marketed as a health remedy.",category:"Food",difficulty:3},
  {text:"Peanuts are legumes rather than true nuts.",answer:true,explanation:"They grow underground and belong to the legume family.",category:"Food",difficulty:2},
  {text:"Almonds are seeds, not true nuts.",answer:true,explanation:"An almond is the seed of a fruit called a drupe.",category:"Food",difficulty:2},
  {text:"Apples float in water because they are about a quarter air.",answer:true,explanation:"Air pockets inside apples make them buoyant.",category:"Food",difficulty:2},
  {text:"The Aztecs used cacao beans as a form of currency.",answer:true,explanation:"Chocolate's source beans were valuable enough to spend.",category:"Food",difficulty:2},
  {text:"Rhubarb leaves are poisonous.",answer:true,explanation:"The leaves contain toxic compounds, though the stalks are edible.",category:"Food",difficulty:2},
  {text:"Nutmeg can be toxic if eaten in large amounts.",answer:true,explanation:"Large doses can cause serious effects on the body.",category:"Food",difficulty:2},
  {text:"Pound cake was originally made with a pound each of its main ingredients.",answer:true,explanation:"Its name comes from the classic one-pound recipe ratio.",category:"Food",difficulty:3},
  {text:"Ripe cranberries can bounce.",answer:true,explanation:"Firm, ripe cranberries bounce, which is used to sort them.",category:"Food",difficulty:2},
  {text:"Cheese is one of the most shoplifted foods in the world.",answer:true,explanation:"Retail studies have repeatedly ranked cheese near the top.",category:"Food",difficulty:3},
  {text:"Pumpkins are botanically fruits.",answer:true,explanation:"They develop from a flower and contain seeds.",category:"Food",difficulty:2},
  {text:"Avocados are botanically berries.",answer:true,explanation:"They fit the botanical definition of a single-seeded berry.",category:"Food",difficulty:2},
  {text:"Watermelon is over 90 percent water.",answer:true,explanation:"Its high water content is where it gets its name.",category:"Food",difficulty:1},
  {text:"Saffron is one of the most expensive spices by weight.",answer:true,explanation:"It must be harvested by hand from crocus flowers.",category:"Food",difficulty:2},
  {text:"Fortune cookies were popularized in the United States rather than China.",answer:true,explanation:"They became famous through Chinese-American restaurants.",category:"Food",difficulty:2},
  {text:"Ketchup began as a fish-based sauce in Asia.",answer:true,explanation:"Early versions were fermented fish sauces, not tomato-based.",category:"Food",difficulty:3},
  {text:"The spiciness of chili peppers is measured in Scoville units.",answer:true,explanation:"The Scoville scale rates heat from capsaicin.",category:"Food",difficulty:2},
  {text:"Popcorn pops because water inside the kernel turns to steam.",answer:true,explanation:"Trapped steam builds pressure until the kernel bursts.",category:"Food",difficulty:1},
  {text:"Tomatoes were once feared as poisonous in parts of Europe.",answer:true,explanation:"Early Europeans wrongly suspected the fruit was dangerous.",category:"Food",difficulty:2},
  {text:"Dark chocolate contains caffeine.",answer:true,explanation:"Cocoa naturally contains a small amount of caffeine.",category:"Food",difficulty:2},

  // ---------- NEW: HISTORY ----------
  {text:"Vikings wore horned helmets in battle.",answer:false,explanation:"There is no evidence Vikings used horned battle helmets; that image came later.",category:"History",difficulty:2},
  {text:"The Titanic sank in 1912.",answer:true,explanation:"It struck an iceberg on its maiden voyage in April 1912.",category:"History",difficulty:1},
  {text:"The Berlin Wall fell in 1989.",answer:true,explanation:"Its opening in November 1989 marked a major turning point in the Cold War.",category:"History",difficulty:1},
  {text:"Julius Caesar was never actually an emperor of Rome.",answer:true,explanation:"He held the title of dictator; the empire began after his death.",category:"History",difficulty:3},
  {text:"The Hundred Years' War lasted more than a hundred years.",answer:true,explanation:"The conflict stretched across about 116 years.",category:"History",difficulty:3},
  {text:"Cleopatra was of Greek Macedonian descent.",answer:true,explanation:"She came from the Ptolemaic dynasty, which was of Greek origin.",category:"History",difficulty:3},
  {text:"The guillotine was named after a man who invented it.",answer:false,explanation:"It was named after a doctor who proposed its use, not its inventor.",category:"History",difficulty:3},
  {text:"The Rosetta Stone helped scholars decode Egyptian hieroglyphs.",answer:true,explanation:"Its parallel texts unlocked the meaning of hieroglyphic writing.",category:"History",difficulty:2},
  {text:"The Wright brothers made their first powered flight in 1903.",answer:true,explanation:"Their historic flight took place at Kitty Hawk in 1903.",category:"History",difficulty:1},
  {text:"Coca-Cola originally contained cocaine.",answer:true,explanation:"Early recipes included a trace derived from the coca leaf.",category:"History",difficulty:2},
  {text:"The typewriter was invented before the telephone.",answer:true,explanation:"A practical typewriter appeared several years before the telephone.",category:"History",difficulty:3},
  {text:"The Eiffel Tower was originally meant to be temporary.",answer:true,explanation:"It was built for a world's fair and nearly dismantled afterward.",category:"History",difficulty:2},
  {text:"The Mona Lisa was stolen from the Louvre in 1911.",answer:true,explanation:"Its theft made the painting even more famous worldwide.",category:"History",difficulty:2},
  {text:"Ancient Egyptians revered cats.",answer:true,explanation:"Cats were honored and associated with certain deities.",category:"History",difficulty:1},
  {text:"The United States declared independence in 1776.",answer:true,explanation:"The Declaration of Independence was adopted in July 1776.",category:"History",difficulty:1},
  {text:"The oldest known individual living trees are thousands of years old.",answer:true,explanation:"Some bristlecone pines have lived for over four thousand years.",category:"History",difficulty:2},
  {text:"The printing press credited to Gutenberg used movable type.",answer:true,explanation:"His movable-type press transformed how books were made.",category:"History",difficulty:2},
  {text:"Ancient Romans used a form of toothpaste.",answer:true,explanation:"They cleaned teeth with abrasive powders and pastes.",category:"History",difficulty:2},
  {text:"Genghis Khan founded the Mongol Empire.",answer:true,explanation:"He united the Mongol tribes and launched a vast empire.",category:"History",difficulty:1},
  {text:"The Roman Colosseum was sometimes flooded for staged naval battles.",answer:true,explanation:"Early events reportedly recreated sea battles inside the arena.",category:"History",difficulty:3},
  {text:"World War I ended in 1918.",answer:true,explanation:"An armistice ended the fighting in November 1918.",category:"History",difficulty:1},
  {text:"Leonardo da Vinci sketched designs for flying machines.",answer:true,explanation:"His notebooks contain concepts centuries ahead of their time.",category:"History",difficulty:2},

  // ---------- NEW: WORLD ----------
  {text:"Russia spans eleven time zones.",answer:true,explanation:"Its enormous width crosses eleven official time zones.",category:"World",difficulty:2},
  {text:"Canada has the longest coastline of any country.",answer:true,explanation:"Its many islands and inlets give it the world's longest coast.",category:"World",difficulty:2},
  {text:"The Dead Sea is so salty that people float easily in it.",answer:true,explanation:"Its high salt content increases the water's buoyancy.",category:"World",difficulty:1},
  {text:"Greenland is the world's largest island.",answer:true,explanation:"It is the biggest land mass classified as an island.",category:"World",difficulty:2},
  {text:"Iceland has almost no native mosquitoes.",answer:true,explanation:"Its climate and conditions leave it nearly mosquito-free.",category:"World",difficulty:3},
  {text:"The Great Barrier Reef is the largest living structure on Earth.",answer:true,explanation:"It is so vast it can be seen from space.",category:"World",difficulty:2},
  {text:"Measured from base to peak, Mount Everest is the tallest mountain on Earth.",answer:false,explanation:"Mauna Kea is taller base to peak; Everest is highest above sea level.",category:"World",difficulty:3},
  {text:"There is a country completely surrounded by South Africa.",answer:true,explanation:"Lesotho is entirely enclosed within South Africa.",category:"World",difficulty:3},
  {text:"Istanbul sits on two continents.",answer:true,explanation:"The city spans both Europe and Asia across a strait.",category:"World",difficulty:2},
  {text:"The deepest known point in the ocean is the Mariana Trench.",answer:true,explanation:"Its lowest point plunges deeper than Everest is tall.",category:"World",difficulty:1},
  {text:"Australia is both a country and a continent.",answer:true,explanation:"It is the only country that is also a whole continent.",category:"World",difficulty:1},
  {text:"Antarctica has no permanent human population.",answer:true,explanation:"Only temporary research staff live there.",category:"World",difficulty:2},
  {text:"Lake Baikal is the deepest freshwater lake in the world.",answer:true,explanation:"It holds an enormous share of the world's fresh surface water.",category:"World",difficulty:3},
  {text:"Death Valley holds some of the hottest temperatures ever recorded on Earth.",answer:true,explanation:"Its desert heat ranks among the most extreme on the planet.",category:"World",difficulty:2},
  {text:"Singapore is both a city and a country.",answer:true,explanation:"It is a rare example of a city-state.",category:"World",difficulty:2},
  {text:"Mongolia is one of the least densely populated countries on Earth.",answer:true,explanation:"Its vast land holds a relatively small population.",category:"World",difficulty:2},
  {text:"The Sahara is the largest hot desert in the world.",answer:true,explanation:"It stretches across much of northern Africa.",category:"World",difficulty:1},
  {text:"Africa is the second-largest continent.",answer:true,explanation:"Only Asia is larger in land area.",category:"World",difficulty:1},
  {text:"Point Nemo is the most remote spot in the ocean from land.",answer:true,explanation:"It lies farther from any coastline than any other ocean point.",category:"World",difficulty:3},
  {text:"Vatican City has its own postal system.",answer:true,explanation:"The tiny state runs its own mail service.",category:"World",difficulty:3},

  // ---------- NEW: TECHNOLOGY ----------
  {text:"The first webcam was set up to watch a coffee pot.",answer:true,explanation:"Researchers used it to check if the pot was full without walking over.",category:"Technology",difficulty:3},
  {text:"Nokia started out making paper products.",answer:true,explanation:"The company began as a paper mill in the 1800s.",category:"Technology",difficulty:3},
  {text:"The first YouTube video was uploaded in 2005.",answer:true,explanation:"An early clip at a zoo marked the site's first upload.",category:"Technology",difficulty:2},
  {text:"Google was originally given a different name before rebranding.",answer:true,explanation:"The project was first called BackRub before becoming Google.",category:"Technology",difficulty:3},
  {text:"The very first text message said 'Merry Christmas.'",answer:true,explanation:"The first SMS, sent in 1992, carried a holiday greeting.",category:"Technology",difficulty:3},
  {text:"The first documented computer 'bug' was an actual insect.",answer:true,explanation:"A moth was found stuck in an early computer's hardware.",category:"Technology",difficulty:2},
  {text:"Email existed before the World Wide Web.",answer:true,explanation:"Email predates the web by more than a decade.",category:"Technology",difficulty:2},
  {text:"Apple's very first logo featured Isaac Newton.",answer:true,explanation:"The original 1976 logo showed Newton under an apple tree.",category:"Technology",difficulty:3},
  {text:"Ada Lovelace is often considered the first computer programmer.",answer:true,explanation:"She wrote an algorithm for an early mechanical computer.",category:"Technology",difficulty:2},
  {text:"Bluetooth is named after a medieval king.",answer:true,explanation:"It is named after a Scandinavian king known as Harald Bluetooth.",category:"Technology",difficulty:3},
  {text:"The first iPhone was released in 2007.",answer:true,explanation:"Apple introduced the original iPhone in 2007.",category:"Technology",difficulty:1},
  {text:"The word 'spam' for junk messages comes from a Monty Python sketch.",answer:true,explanation:"The comedy sketch's repeated word became the term for junk email.",category:"Technology",difficulty:3},
  {text:"A byte is made up of eight bits.",answer:true,explanation:"Eight bits form one standard byte.",category:"Technology",difficulty:2},
  {text:"QR codes were invented in Japan.",answer:true,explanation:"They were created by a Japanese company for tracking parts.",category:"Technology",difficulty:2},
  {text:"The word 'robot' comes from a Czech play.",answer:true,explanation:"It was popularized by a 1920s play from Czechoslovakia.",category:"Technology",difficulty:3},
  {text:"Emojis originated in Japan.",answer:true,explanation:"The first widely used emoji sets were developed in Japan.",category:"Technology",difficulty:2},
  {text:"The floppy disk save icon is based on a real physical object.",answer:true,explanation:"It depicts an actual floppy disk once used for storage.",category:"Technology",difficulty:1},
  {text:"A large share of internet traffic comes from automated bots rather than humans.",answer:true,explanation:"Bots account for a substantial portion of web activity.",category:"Technology",difficulty:3},
  {text:"The very first webpage is still accessible online.",answer:true,explanation:"The original web page has been preserved and restored.",category:"Technology",difficulty:3},
  {text:"Wikipedia is written and edited by volunteers around the world.",answer:true,explanation:"Its content is created and maintained by unpaid contributors.",category:"Technology",difficulty:1},

  // ---------- NEW: GAMING ----------
  {text:"Minecraft is one of the best-selling video games of all time.",answer:true,explanation:"It has sold hundreds of millions of copies worldwide.",category:"Gaming",difficulty:1},
  {text:"The character Mario first appeared in Donkey Kong.",answer:true,explanation:"He debuted there before starring in his own series.",category:"Gaming",difficulty:2},
  {text:"Mario was originally called Jumpman.",answer:true,explanation:"His early name was Jumpman before he became Mario.",category:"Gaming",difficulty:3},
  {text:"Sonic the Hedgehog was created as Sega's mascot.",answer:true,explanation:"He was designed to be Sega's flagship character.",category:"Gaming",difficulty:2},
  {text:"Pong was one of the first commercially successful video games.",answer:true,explanation:"Its simple tennis-style play helped launch the industry.",category:"Gaming",difficulty:2},
  {text:"A Game Boy that survived a bombing during the Gulf War still powers on.",answer:true,explanation:"The damaged unit is displayed and reportedly still works.",category:"Gaming",difficulty:3},
  {text:"Lara Croft is the protagonist of the Tomb Raider series.",answer:true,explanation:"She is the adventurer at the center of the games.",category:"Gaming",difficulty:1},
  {text:"The PlayStation began as a planned add-on for a Nintendo console.",answer:true,explanation:"A collaboration fell apart, and the project became its own console.",category:"Gaming",difficulty:3},
  {text:"Copies of the Atari game based on E.T. were buried in a landfill.",answer:true,explanation:"Unsold cartridges were dumped and later excavated.",category:"Gaming",difficulty:3},
  {text:"The word 'Pokemon' is short for Pocket Monsters.",answer:true,explanation:"The name is a contraction of the original Japanese title.",category:"Gaming",difficulty:2},
  {text:"The original Legend of Zelda was released in the 1980s.",answer:true,explanation:"The first Zelda game launched in the mid-1980s.",category:"Gaming",difficulty:2},
  {text:"Windows once included Solitaire partly to help people practice using a mouse.",answer:true,explanation:"It doubled as a fun way to learn drag-and-drop control.",category:"Gaming",difficulty:3},
  {text:"Minecraft was created by a developer known as Notch.",answer:true,explanation:"Markus Persson, known as Notch, built the original game.",category:"Gaming",difficulty:2},
  {text:"The Sims lets players simulate everyday life.",answer:true,explanation:"Players guide virtual people through daily routines.",category:"Gaming",difficulty:1},
  {text:"Grand Theft Auto V is one of the best-selling video games ever.",answer:true,explanation:"It has sold well over a hundred million copies.",category:"Gaming",difficulty:2},
  {text:"The Nintendo Wii used the code name Revolution during development.",answer:true,explanation:"It was known as Revolution before its final name.",category:"Gaming",difficulty:3},

  // ---------- NEW: GAMES (board & card) ----------
  {text:"Chess is generally believed to have originated in India.",answer:true,explanation:"It evolved from an early Indian game called chaturanga.",category:"Games",difficulty:2},
  {text:"Monopoly was based on an earlier game about land ownership.",answer:true,explanation:"It descends from a game called The Landlord's Game.",category:"Games",difficulty:3},
  {text:"A chessboard has 64 squares.",answer:true,explanation:"It is an eight-by-eight grid of squares.",category:"Games",difficulty:1},
  {text:"In chess, the queen is the most powerful piece.",answer:true,explanation:"She can move any number of squares in many directions.",category:"Games",difficulty:1},
  {text:"The game of Go is older than chess.",answer:true,explanation:"Go has been played for thousands of years, predating chess.",category:"Games",difficulty:2},
  {text:"A Rubik's Cube has more than 43 quintillion possible arrangements.",answer:true,explanation:"The number of scrambled states is astronomically large.",category:"Games",difficulty:3},
  {text:"A royal flush is the highest hand in standard poker.",answer:true,explanation:"No standard hand ranks above a royal flush.",category:"Games",difficulty:2},
  {text:"Backgammon is one of the oldest known board games.",answer:true,explanation:"Versions of it have been played for thousands of years.",category:"Games",difficulty:2},
  {text:"The dots on dice are called pips.",answer:true,explanation:"Pip is the term for each marked spot.",category:"Games",difficulty:2},
  {text:"The name Jenga comes from a Swahili word meaning to build.",answer:true,explanation:"Jenga is derived from the Swahili verb for building.",category:"Games",difficulty:3},
  {text:"Dominoes are thought to have originated in China.",answer:true,explanation:"Early forms of the tiles trace back to China.",category:"Games",difficulty:2},
  {text:"Scrabble tile values are based on how common each letter is.",answer:true,explanation:"Rarer letters are worth more points.",category:"Games",difficulty:2},

  // ---------- NEW: SPORTS ----------
  {text:"Basketball was originally played using peach baskets.",answer:true,explanation:"The first games used actual peach baskets as goals.",category:"Sports",difficulty:2},
  {text:"The five Olympic rings represent five parts of the world.",answer:true,explanation:"They symbolize the union of continents in the Games.",category:"Sports",difficulty:2},
  {text:"A marathon is about 26.2 miles long.",answer:true,explanation:"The standard marathon distance is roughly 26.2 miles.",category:"Sports",difficulty:1},
  {text:"Golf is the only sport that has been played on the Moon.",answer:true,explanation:"An astronaut famously hit golf balls on the lunar surface.",category:"Sports",difficulty:3},
  {text:"Boxing rings are actually square.",answer:true,explanation:"Despite the name, a boxing 'ring' is square.",category:"Sports",difficulty:2},
  {text:"Sumo wrestling originated in Japan.",answer:true,explanation:"It is a traditional Japanese sport with deep cultural roots.",category:"Sports",difficulty:1},
  {text:"The FIFA World Cup is held every four years.",answer:true,explanation:"The men's tournament takes place on a four-year cycle.",category:"Sports",difficulty:1},
  {text:"A Test match in cricket can last up to five days.",answer:true,explanation:"Test cricket is played over as many as five days.",category:"Sports",difficulty:2},
  {text:"A hat-trick means scoring three goals in a single game.",answer:true,explanation:"The term describes three goals by one player in one match.",category:"Sports",difficulty:2},
  {text:"Wimbledon tennis is played on grass courts.",answer:true,explanation:"It is the major tournament still played on grass.",category:"Sports",difficulty:2},
  {text:"Ice hockey is played with a puck rather than a ball.",answer:true,explanation:"Players use a flat rubber puck on the ice.",category:"Sports",difficulty:1},
  {text:"In theory, a Formula 1 car generates enough downforce to drive upside down.",answer:true,explanation:"At high speed its downforce can exceed its own weight.",category:"Sports",difficulty:3},
  {text:"Standard basketball hoops are set ten feet above the floor.",answer:true,explanation:"The rim height has long been fixed at ten feet.",category:"Sports",difficulty:2},
  {text:"A badminton shuttlecock can travel faster than 200 miles per hour.",answer:true,explanation:"Powerful smashes have topped 200 miles per hour.",category:"Sports",difficulty:3},
  {text:"The Tour de France is a cycling race.",answer:true,explanation:"It is one of cycling's most famous multi-stage races.",category:"Sports",difficulty:1},
  {text:"Table tennis is an Olympic sport.",answer:true,explanation:"It has been part of the Olympic program for decades.",category:"Sports",difficulty:2},

  // ---------- NEW: FALSE-CLAIM MISCONCEPTIONS (to balance the game) ----------
  {text:"Ostriches bury their heads in the sand when they are scared.",answer:false,explanation:"They lower their heads to tend nests or eat, but never bury them in fear.",category:"Animals",difficulty:1},
  {text:"A goldfish will only ever grow to the size of its bowl.",answer:false,explanation:"Goldfish keep growing in larger spaces; a small bowl just stunts them unhealthily.",category:"Animals",difficulty:2},
  {text:"A mother bird will abandon a chick if a human touches it.",answer:false,explanation:"Most birds have a weak sense of smell and will not reject a touched chick.",category:"Animals",difficulty:2},
  {text:"Sharks are incapable of getting cancer.",answer:false,explanation:"Sharks can and do develop cancer; this is a persistent myth.",category:"Animals",difficulty:2},
  {text:"Elephants are naturally terrified of mice.",answer:false,explanation:"There is no solid evidence elephants have a special fear of mice.",category:"Animals",difficulty:2},
  {text:"A dog's mouth is cleaner than a human's mouth.",answer:false,explanation:"Both mouths carry plenty of bacteria; neither is truly cleaner.",category:"Animals",difficulty:2},
  {text:"Porcupines can shoot their quills at attackers.",answer:false,explanation:"Quills detach on contact but cannot be launched through the air.",category:"Animals",difficulty:2},
  {text:"An owl can rotate its head a full 360 degrees.",answer:false,explanation:"Owls can turn their heads about 270 degrees, not all the way around.",category:"Animals",difficulty:2},
  {text:"Adult cats should be given cow's milk as a healthy treat.",answer:false,explanation:"Many cats are lactose intolerant, and milk can upset their stomachs.",category:"Animals",difficulty:2},
  {text:"Touching a frog or toad gives you warts.",answer:false,explanation:"Warts come from a human virus, not from amphibians.",category:"Animals",difficulty:1},
  {text:"Snakes feel slimy to the touch.",answer:false,explanation:"Snake scales are dry and smooth, not slimy.",category:"Animals",difficulty:1},
  {text:"Wolves howl at the Moon.",answer:false,explanation:"Wolves howl to communicate, not because of the Moon.",category:"Animals",difficulty:2},
  {text:"Cutting an earthworm in half reliably creates two living worms.",answer:false,explanation:"Usually only the head end may survive; the other part dies.",category:"Animals",difficulty:2},
  {text:"Houseflies live for only 24 hours.",answer:false,explanation:"Common houseflies typically live for several weeks.",category:"Animals",difficulty:2},
  {text:"Penguins live at the North Pole.",answer:false,explanation:"Wild penguins live in the Southern Hemisphere, not the Arctic.",category:"Animals",difficulty:1},
  {text:"Polar bears and penguins live side by side in the wild.",answer:false,explanation:"Polar bears live in the Arctic; penguins live far to the south.",category:"Animals",difficulty:1},
  {text:"A group of lions is called a herd.",answer:false,explanation:"A group of lions is called a pride.",category:"Animals",difficulty:1},
  {text:"Bats are always carriers of rabies.",answer:false,explanation:"Only a small fraction of bats carry rabies.",category:"Animals",difficulty:2},
  {text:"Daddy longlegs are the most venomous spiders but simply can't bite people.",answer:false,explanation:"This popular claim is false, and many daddy longlegs aren't even spiders.",category:"Animals",difficulty:3},
  {text:"A honeybee dies after every single sting it delivers.",answer:false,explanation:"They die stinging thick-skinned animals, but can sting insects without dying.",category:"Animals",difficulty:3},
  {text:"Shaving hair makes it grow back thicker and darker.",answer:false,explanation:"Shaving only blunts the tip; it doesn't change hair thickness or color.",category:"Body",difficulty:1},
  {text:"Cracking your knuckles causes arthritis.",answer:false,explanation:"Studies have not found a link between knuckle cracking and arthritis.",category:"Body",difficulty:1},
  {text:"Humans have exactly five senses and no more.",answer:false,explanation:"We also sense balance, temperature, pain, body position, and more.",category:"Body",difficulty:2},
  {text:"You lose most of your body heat through your head.",answer:false,explanation:"Heat loss is roughly proportional to exposed skin, not concentrated in the head.",category:"Body",difficulty:2},
  {text:"Reading in dim light permanently damages your eyesight.",answer:false,explanation:"It may cause temporary strain but does not cause lasting damage.",category:"Body",difficulty:2},
  {text:"Eating sugar makes children hyperactive.",answer:false,explanation:"Controlled studies have not found sugar to cause hyperactivity.",category:"Body",difficulty:2},
  {text:"Everyone must drink exactly eight glasses of water every day.",answer:false,explanation:"Needs vary by person; there is no strict universal rule.",category:"Body",difficulty:2},
  {text:"The tongue has separate zones that each detect one taste.",answer:false,explanation:"Taste receptors for all basic tastes are spread across the tongue.",category:"Body",difficulty:2},
  {text:"Swallowed chewing gum stays in your stomach for seven years.",answer:false,explanation:"Gum passes through the digestive system like other material.",category:"Body",difficulty:1},
  {text:"Cold weather itself gives you the common cold.",answer:false,explanation:"Colds are caused by viruses, not by being cold.",category:"Body",difficulty:1},
  {text:"The five-second rule makes dropped food safe to eat.",answer:false,explanation:"Bacteria can transfer to food almost instantly.",category:"Body",difficulty:1},
  {text:"Stomach ulcers are caused mainly by stress and spicy food.",answer:false,explanation:"Most ulcers are caused by a bacterial infection or certain medicines.",category:"Body",difficulty:2},
  {text:"People are either strictly left-brained or right-brained by personality.",answer:false,explanation:"Both hemispheres work together; the strict divide is a myth.",category:"Body",difficulty:2},
  {text:"Drinking coffee stunts a child's growth.",answer:false,explanation:"There is no solid evidence that coffee affects height.",category:"Body",difficulty:2},
  {text:"Turkey is the main reason people feel sleepy after a big holiday meal.",answer:false,explanation:"The heavy meal overall, not the turkey specifically, causes drowsiness.",category:"Body",difficulty:3},
  {text:"A penny dropped from a skyscraper could kill a person below.",answer:false,explanation:"A penny is too light and unstable to reach a lethal speed.",category:"Science",difficulty:2},
  {text:"The Sun burns like a giant bonfire.",answer:false,explanation:"The Sun produces energy through nuclear fusion, not fire.",category:"Science",difficulty:2},
  {text:"Diamonds are formed from coal.",answer:false,explanation:"Most diamonds form from carbon deep in the mantle, unrelated to coal.",category:"Science",difficulty:3},
  {text:"Seasons happen because Earth gets closer to the Sun in summer.",answer:false,explanation:"Seasons are caused by Earth's tilt, not its distance from the Sun.",category:"Science",difficulty:2},
  {text:"There is no gravity at all in space near Earth.",answer:false,explanation:"Astronauts float because they are in constant free fall, not because gravity is gone.",category:"Space",difficulty:2},
  {text:"The North Star is the brightest star in the night sky.",answer:false,explanation:"Sirius is the brightest; the North Star is valued for its position.",category:"Space",difficulty:2},
  {text:"Sound travels faster than light.",answer:false,explanation:"Light is vastly faster than sound.",category:"Science",difficulty:1},
  {text:"Antibiotics are an effective treatment for the common cold.",answer:false,explanation:"Colds are viral, and antibiotics only work on bacteria.",category:"Science",difficulty:1},
  {text:"Microwaves cook food from the inside out.",answer:false,explanation:"They heat water molecules mostly near the surface, which spreads inward.",category:"Science",difficulty:2},
  {text:"A compass needle points to the true geographic North Pole.",answer:false,explanation:"It points toward the magnetic pole, which is a different spot.",category:"Science",difficulty:2},
  {text:"Meteorites are scorching hot to the touch right after they land.",answer:false,explanation:"Many are cold, since deep space chills them and the fall is brief.",category:"Space",difficulty:3},
  {text:"Seasons occur at the same time in the Northern and Southern Hemispheres.",answer:false,explanation:"The hemispheres experience opposite seasons.",category:"World",difficulty:1},
  {text:"Albert Einstein failed mathematics as a student.",answer:false,explanation:"He actually excelled at math from a young age.",category:"History",difficulty:2},
  {text:"Thomas Edison invented the light bulb entirely by himself.",answer:false,explanation:"He improved on earlier designs by many other inventors.",category:"History",difficulty:2},
  {text:"Columbus proved the Earth was round while others believed it was flat.",answer:false,explanation:"Educated people already knew the Earth was round.",category:"History",difficulty:2},
  {text:"Marie Antoinette is documented as saying 'Let them eat cake.'",answer:false,explanation:"There is no reliable evidence she ever said it.",category:"History",difficulty:2},
  {text:"Benjamin Franklin served as a President of the United States.",answer:false,explanation:"He was a founding figure but never president.",category:"History",difficulty:1},
  {text:"The capital of Australia is Sydney.",answer:false,explanation:"Canberra is Australia's capital.",category:"World",difficulty:1},
  {text:"The capital of Brazil is Rio de Janeiro.",answer:false,explanation:"Brasília is Brazil's capital.",category:"World",difficulty:2},
  {text:"The capital of Turkey is Istanbul.",answer:false,explanation:"Ankara is Turkey's capital.",category:"World",difficulty:2},
  {text:"Mount Kilimanjaro is located in Asia.",answer:false,explanation:"Kilimanjaro is in Africa.",category:"World",difficulty:1},
  {text:"New York City is the capital of the United States.",answer:false,explanation:"Washington, D.C. is the capital.",category:"World",difficulty:1},
  {text:"Africa is a single country.",answer:false,explanation:"Africa is a continent made up of many countries.",category:"World",difficulty:1},
  {text:"Europe is larger than Asia in land area.",answer:false,explanation:"Asia is far larger than Europe.",category:"World",difficulty:1},
  {text:"The Pacific is the smallest ocean on Earth.",answer:false,explanation:"The Pacific is the largest ocean.",category:"World",difficulty:1},
  {text:"Mount Everest is located in Africa.",answer:false,explanation:"Everest sits in Asia, in the Himalayas.",category:"World",difficulty:1},
  {text:"Canada is smaller than the United States in total area.",answer:false,explanation:"Canada is larger than the U.S. in total area.",category:"World",difficulty:2},
  {text:"The Amazon rainforest lies mostly outside Brazil.",answer:false,explanation:"The majority of the Amazon rainforest is within Brazil.",category:"World",difficulty:2},
  {text:"The Leaning Tower of Pisa was deliberately built to lean.",answer:false,explanation:"It began tilting during construction due to unstable ground.",category:"World",difficulty:2},
  {text:"Big Ben is the official name of the famous London clock tower.",answer:false,explanation:"Big Ben refers to the great bell; the tower is the Elizabeth Tower.",category:"World",difficulty:3},
  {text:"Adding oil to pasta water is essential to keep the pasta from sticking.",answer:false,explanation:"Stirring works better; oil mostly floats and does little.",category:"Food",difficulty:2},
  {text:"Searing meat seals in its juices.",answer:false,explanation:"Searing adds flavor and browning but does not lock in moisture.",category:"Food",difficulty:2},
  {text:"All the alcohol cooks out of food during cooking.",answer:false,explanation:"Some alcohol can remain depending on the cooking time and method.",category:"Food",difficulty:2},
  {text:"Fresh vegetables are always more nutritious than frozen ones.",answer:false,explanation:"Frozen vegetables can be just as nutritious, sometimes more so.",category:"Food",difficulty:2},
  {text:"MSG has been scientifically proven to be dangerous for most people.",answer:false,explanation:"Research has not shown MSG to be harmful in normal amounts.",category:"Food",difficulty:3},
  {text:"Brown eggs are more nutritious than white eggs.",answer:false,explanation:"Shell color reflects the hen's breed, not nutrition.",category:"Food",difficulty:1},
  {text:"Lobsters scream in pain when dropped into boiling water.",answer:false,explanation:"Lobsters cannot scream; the sound is escaping steam or air.",category:"Food",difficulty:2},
  {text:"The word sushi always means raw fish.",answer:false,explanation:"Sushi refers to the seasoned rice; not all sushi contains raw fish.",category:"Food",difficulty:2},
  {text:"Honey is a safe food to give to babies under one year old.",answer:false,explanation:"It can carry bacteria dangerous to infants and should be avoided.",category:"Food",difficulty:3},
  {text:"Bananas grow on trees.",answer:false,explanation:"Banana plants are giant herbs, not true trees.",category:"Food",difficulty:2},
  {text:"Peanuts grow on trees like most nuts.",answer:false,explanation:"Peanuts grow underground.",category:"Food",difficulty:2},
  {text:"Chocolate is toxic to humans in normal amounts.",answer:false,explanation:"It is toxic to some pets, but safe for people in normal amounts.",category:"Food",difficulty:2},
  {text:"Spinach contains dramatically more iron than nearly any other food.",answer:false,explanation:"It is a decent iron source, but the extreme claim traces to an old error.",category:"Food",difficulty:3},
  {text:"Apple computers cannot get viruses or malware at all.",answer:false,explanation:"Macs can be targeted by malware like any computer.",category:"Technology",difficulty:2},
  {text:"Incognito or private browsing makes you completely anonymous online.",answer:false,explanation:"It hides local history but does not make you invisible to sites or networks.",category:"Technology",difficulty:2},
  {text:"You must fully drain a phone battery before recharging it.",answer:false,explanation:"Modern batteries do not need full discharge cycles.",category:"Technology",difficulty:2},
  {text:"More megapixels always means a better camera.",answer:false,explanation:"Sensor size, lens, and processing matter as much or more.",category:"Technology",difficulty:2},
  {text:"5G mobile networks can spread viruses.",answer:false,explanation:"Radio signals cannot transmit biological viruses.",category:"Technology",difficulty:1},
  {text:"The internet and the World Wide Web are exactly the same thing.",answer:false,explanation:"The web is one service that runs on top of the internet.",category:"Technology",difficulty:2},
  {text:"Deleting a file instantly and permanently wipes it from the drive.",answer:false,explanation:"Deleted data often lingers until it is overwritten.",category:"Technology",difficulty:2},
  {text:"Pac-Man's four ghosts all move completely at random.",answer:false,explanation:"Each ghost follows its own distinct chasing behavior.",category:"Gaming",difficulty:3},
  {text:"Video games were first invented in the 1990s.",answer:false,explanation:"Playable video games existed decades earlier.",category:"Gaming",difficulty:2},
  {text:"In chess, the king is the most powerful piece on the board.",answer:false,explanation:"The queen is the most powerful; the king is the most important.",category:"Games",difficulty:1},
  {text:"In chess, pawns are allowed to move backward.",answer:false,explanation:"Pawns can only move forward.",category:"Games",difficulty:2},
  {text:"A game of checkers is played on a board of 100 squares.",answer:false,explanation:"Standard checkers uses a 64-square board.",category:"Games",difficulty:2},
  {text:"A standard soccer match is divided into four quarters.",answer:false,explanation:"Soccer is played in two halves.",category:"Sports",difficulty:1},
  {text:"In American football, a touchdown is worth ten points.",answer:false,explanation:"A touchdown is worth six points.",category:"Sports",difficulty:2},
  {text:"A standard marathon is exactly 25 miles long.",answer:false,explanation:"The official distance is about 26.2 miles.",category:"Sports",difficulty:2},
  {text:"The Summer Olympics are held every single year.",answer:false,explanation:"Each edition of the Games is held every four years.",category:"Sports",difficulty:1},
  {text:"A perfect game in ten-pin bowling scores 100.",answer:false,explanation:"A perfect game scores 300.",category:"Sports",difficulty:2},
  {text:"The Super Bowl decides the world champion of soccer.",answer:false,explanation:"The Super Bowl is the championship of American football.",category:"Sports",difficulty:1},
  {text:"Humans evolved directly from the monkeys we see today.",answer:false,explanation:"Humans and modern monkeys share a common ancestor instead.",category:"Science",difficulty:2},
  {text:"Lightning only travels downward from the clouds to the ground.",answer:false,explanation:"Lightning can also move upward and between clouds.",category:"Science",difficulty:3},
  {text:"A chameleon can perfectly match any background pattern it sees.",answer:false,explanation:"Their color changes are limited and driven mostly by mood and temperature.",category:"Animals",difficulty:2},
  {text:"Water always drains in a fixed direction because of Earth's rotation.",answer:false,explanation:"At sink scale, basin shape matters far more than Earth's spin.",category:"Science",difficulty:3},
  {text:"Goldfish are the only fish that cannot see color.",answer:false,explanation:"Goldfish actually have strong color vision.",category:"Animals",difficulty:3},
  {text:"The Sahara Desert is located in South America.",answer:false,explanation:"The Sahara is in northern Africa.",category:"World",difficulty:1},
  {text:"Twinkies stay fresh for several decades on the shelf.",answer:false,explanation:"Their real shelf life is measured in weeks, not decades.",category:"Food",difficulty:2}
];
